name: Run Newman Tests

# Trigger workflow saat push ke branch main dan pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  newman-test:
    runs-on: ubuntu-latest  # OS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # ambil kode repo

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # versi node yang dipakai

      - name: Install Newman
        run: npm install -g newman  # install newman global

      - name: Run Newman Collection Tests
        run: |
          newman run Swagger\ Petstore.postman_collection.json -r cli,html --reporter-html-export newman-report.html

      - name: Upload HTML Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html

